### PR TITLE
upgrade pnetcdf

### PR DESCRIPTION
**Pull request by mmiesch**
I'm finding that our old version of pnetcdf does not build with gnu 9.3 and openmpi 4.0.3.  But this update does work,  both for Mac and ubuntu 18 (container)

### CODE REVIEW

**Comment by mmiesch** [comment]
@rhoneyager - sure - do you have a particular version in mind that's stable and that we're pretty sure will work with JEDI?

**Comment by mmiesch** [comment]
Ok - we can try 4.7.4 for netcdf and 1.12.0 for hdf5.

**Comment by rhoneyager** [comment]
Let's try with those, with a fallback to HDF5 1.10.6 if an older HDF5 is needed.

**Comment by mmiesch** [comment]
Ok - I'm building a new gnu-openmpi container that has these inside, along with updated versions of eckit, ecbuild, and odc.  I'll do some testing on that.

**Comment by mmiesch** [comment]
Hold off on merging - pnetcdf and hdf 1.12 installed fine on my mac but netcdf 4.7.4 is giving problems - this could be the same C++ integer type definitions we were running into recently.  This is with gnu 9.3/openmpi 4.0.3.  That combination works fine in the ubuntu 18 container.

```
, std::vector<long, std::allocator<long> > const&, unsigned long long const*) const in ncVar.o
  "_nc_put_vars_ushort", referenced from:
      netCDF::NcVar::putVar(std::vector<unsigned long, std::allocator<unsigned long> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, std::vector<long, std::allocator<long> > const&, unsigned short const*) const in ncVar.o
  "_nc_redef", referenced from:
      netCDF::ncCheckDefineMode(int)   in ncCheck.o
      netCDF::NcFile::redef()    in ncFile.o
  "_nc_rename_dim", referenced from:
      netCDF::NcDim::rename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in ncDim.o
  "_nc_rename_var", referenced from:
      netCDF::NcVar::rename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const in ncVar.o
  "_nc_set_fill", referenced from:
      netCDF::NcFile::set_Fill(int, int*) in ncFile.o
  "_nc_set_var_chunk_cache", referenced from:
      netCDF::NcVar::setChunkCache(unsigned long, unsigned long, float) const in ncVar.o
  "_nc_strerror", referenced from:
      netCDF::ncCheck(int, char const*, int) in ncCheck.o
  "_nc_sync", referenced from:
      netCDF::NcFile::sync()    in ncFile.o
  "_nctypelen", referenced from:
      netCDF::NcVar::getTypeLen(int) const in ncVar.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [libnetcdf_c++4.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
BUILD FAIL!  Lib: netcdf-4.7.4 Error:2
```

**Comment by markjolah** [comment]
I am also having problems building `parallelio-2.5.0` against `netcdf-4.7.4`, but `netcdf-4.7.3` does work.

**Comment by rhoneyager** [comment]
> Unfortunately I don't think `hdf5-1.12.0` works with [`h5py-2.10.0`](https://www.h5py.org/) yet. I am getting compile errors like:
> 
> ```
> In file included from /usr/include/H5public.h:32,
>                  from /usr/include/hdf5.h:22,
>                  from /var/tmp/portage/dev-python/h5py-2.10.0-r1/work/h5py-2.10.0/h5py/api_compat.h:27,
>                  from /var/tmp/portage/dev-python/h5py-2.10.0-r1/work/h5py-2.10.0/h5py/defs.c:643:
> /var/tmp/portage/dev-python/h5py-2.10.0-r1/work/h5py-2.10.0/h5py/defs.c: In function ‘__pyx_f_4h5py_4defs_H5Oget_info_by_name’:
> /var/tmp/portage/dev-python/h5py-2.10.0-r1/work/h5py-2.10.0/h5py/defs.c:16577:15: error: too few arguments to function ‘H5Oget_info_by_name3’
> 16577 |   __pyx_t_1 = H5Oget_info_by_name(__pyx_v_loc_id, __pyx_v_name, __pyx_v_oinfo, __pyx_v_lapl_id); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1520, __pyx_L1_error)
> ```
> 
> I am OK with `hdf5-1.10.6` which has been working for me. If we can get `h5py` to compile against `hdf5-1.12.0` I think the upgrade could work for me then.

Looks like HDF5 changed that function recently. I'm fine with using 1.10.* for now.

**Comment by mmiesch** [comment]
I'm good with hdf5 1.10.6.  Also, I determined that what was causing problems on the Mac is *not* version 4.7.4 of nectdf-c, but version 4.3.1 of netcdf-c++.  If I use 4.3.0 of the C++ libraries, then 4.7.3 builds on my Mac (probably 4.7.4 too but I didn't try because of the problems reported above)

**Comment by srherbener** [comment]
I'm good with netcdf 4.7.3 and hdf5 1.10.6. Thanks for testing the newer versions and getting this worked out!

**Comment by mmiesch** [comment]
This combination works on my Mac with gnu 9.3.0/openmpi 4.0.3.  Everything builds and all ufo-bundle tests pass.
